### ISSUE TITLE
Create Search Feature Mock Ups

### ISSUE THREAD

**Issue by KianBadie** [caltechlibrary/cell-atlas#23]
Create mock ups for upcoming search feature and decide on style/layout.

**Comment by KianBadie** [comment]
@coiko I've made a couple of different mocks of some ideas for the search bar on desktop. You can see what they would look like on the site here: https://www.figma.com/proto/SJo426n282Uz54qEwAFicL/Search-Mockups?node-id=2%3A2&scaling=min-zoom&page-id=0%3A1. I have also attached a screenshot of the current search bar ideas so far for reference. Any thoughts on what is shown so far? Do you think any of these are in the right direction or could use some tweaks?

## Screenshot
![types](https://user-images.githubusercontent.com/18221058/135355082-dc6aac1c-b525-45c3-8594-5bcc8f1753a0.PNG)

**Comment by KianBadie** [comment]
@coiko I also started on some mock ups for the result list available here: https://www.figma.com/proto/SJo426n282Uz54qEwAFicL/Search-Mockups?node-id=25%3A83&scaling=min-zoom&page-id=25%3A64. I think I have some more ideas/tweaks for the result menu, so hopefully I can get some more options in that link. For now, I just wanted to throw those out there to see if you had any thoughts so far.

**Comment by coiko** [comment]
Ooh I like these!  Thanks @KianBadie!  I think my favorite is number 6 (rounded boundary with grey text).  The only thought I have is that it might be cool to add some animation, so that it would be more minimal (maybe just the magnifying glass icon) until it's selected, when the full bar would pop out.  What do you think?

**Comment by KianBadie** [comment]
@coiko Sounds good! So if I'm understanding you correctly, would the magnifying glass be centered until it is clicked? Then it would expand fully to reveal the search bar?

**Comment by coiko** [comment]
@KianBadie Oh those results mocks look fantastic!  I love the white version - either number 3 or 4.  Which do you like?

And yes, if you want to try an animation, it would probably make most sense to have the magnifying glass centered.

**Comment by KianBadie** [comment]
@coiko I like both the black/white version, so whichever one you like more is the one I am a fan of! As for the overlay background, I  added that in there to mimic some sites I saw. I'm not sure how necessary it is though, so I'm on the fence about "needing" it at the moment. I will let it roll around my head a bit. Do you have any thoughts?

**Comment by KianBadie** [comment]
@coiko There were also some details I wanted to ask about the displayed results list:

- I assumed that by default, all the document metadata (species, collector, structure) would display by default in a result (if it had that data). I did this because if only the content containing the search keyword would be shown, I wasn't sure how to display a result that only had the key word in the metadata (for example, if someone searched for "Morgan", would the displayed result only show the title and collector field?). So it seemed easier presentation wise. What do you think about this?
- If the returned list is short, should there be a fixed height with empty space up until some max height? Or should the list only be as tall as needed until it reaches a max height?

**Comment by coiko** [comment]
Thanks @KianBadie!  (And sorry for the slow response!)  I think the white version is great, and I don't think the overlay background is necessary, so let's keep it simple and leave it off (at least for now).

And no, I think the styling of the result list is fantastic!

As for the details, yes, I think it's a great idea to show the metadata in case that's what someone's searching for.  And as for height, I think it's fine to only have it as tall as needed to accommodate the results (unless you prefer a minimum height).  Since it's an overlay element, I think it will look good even when it's very short.

**Comment by KianBadie** [comment]
@coiko No worries  at all! And sounds good! I will go ahead and stick with the white version of the results list and only experiment with new ideas if it seems like a great idea.

For the metadata question, I think I might have miscommunicated my question! I was wondering if the result was only in the metadata, should the main content of the section still show? And sounds good on the height!

**Comment by coiko** [comment]
@KianBadie Ah, sorry for misunderstanding that!  Yes, I think it's good to show the main content of the section to provide a little more context.  But if it looks odd to you, feel free to leave it off.  Thanks!

**Comment by KianBadie** [comment]
@coiko No worries! That sounds good to me. I also agree that it feels better to include the content of the section.

**Comment by KianBadie** [comment]
@coiko So I created some mocks for the mobile design of the search feature: https://www.figma.com/proto/SJo426n282Uz54qEwAFicL/Search-Mockups?node-id=64%3A308&scaling=scale-down&page-id=56%3A245. It's only testing 1 idea so far, which is to have the search bar take over the title when it is clicked. I'm not sure how that transition would look visually however. Also, I made the mocks using an iPhone 8 with the navigation bars showing to work with an example that would be on the lower end of screen space. The android navigation bars resulted in a similar layout to iOS, so I think the end result will be the same.

Here are some other ideas I had for mobile with inspiration examples. Of course, the examples are best seen on mobile sized screens. So you might have to view them on your phone, if you were interested in the ideas!:
- search bar/results can be in nav menu (example: https://www.gamespot.com/)
   - results replace navigation content
   - the navigation menu might have to take up more horizontal space to show results nicely. It could do this by default, or maybe grow when the search bar is clicked
-  there could be some sort of modal that appears on the page to contain search bar and results (example: https://www.gatsbyjs.com/docs/)
   - still need a place for search icon to click on to open modal
   - benefit of that is that only icon needs to be displayed
 - the style in the mocks I shared (example: https://www.amazon.com/)
    - might make header cramped on portrait

As a side note, I thought the gamespot and gatsbyjs examples were really cool. As of right now, I don't think I have any strong opinions formed yet amongst the 3 ideas, so I don't mean that in a way to sway opinions yet! I just thought it was really interesting how they made use of the layout space on mobile.

Did you have any other ideas for the search on mobile? I took some notes from our discussion, but I am sorry to say that they were not very good notes so I might have missed some key points. It looks like some ideas were to remove the title in the header or to even remove search on mobile. Another option was to put search in a new page (could maybe be just results or the whole feature in general), but I opted to save that as a backup, since it would be a different experience from desktop (adding a new page to the experience). Do you have any opinions or thoughts on what I have mentioned so far? Were there any ideas from our discussion I missed? I will be creating mocks for the other ideas to see how they pan out, but feel free to let me know if you think some of the ideas are not worth investing in!

**Comment by coiko** [comment]
@KianBadie Never apologize for updates!  They're _always_ greatly appreciated!  I apologize for another (the last, I hope) long delay.

These examples are fantastic!  I agree with you - my favorites are the nav menu and mobile options (gamespot and gatsby).  The Amazon-style page element clutters up the page too much.  And yes, I like the idea of not making it a separate page on mobile.  

I love the mocks you developed!  Both of them look great.  The simplest/cleanest option might be the nav menu element.  That leaves all the real estate in the header for your nice styling with the page title.  If that's more complicated to implement, though (since it involves a bigger change from desktop), we should go with the header icon.

The  styling of the results also looks fantastic.  I like the site-theme color highlighting.  I agree that it would be good to show that they're clickable links, so yes, underlining the title (and having that be the link) would be perfect!

**Comment by KianBadie** [comment]
@coiko As always, no worries on the delay!

Having the search feature in the nav menu would require some additional tweaks since we would have the feature in 2 spots, but not so much that it should be considered a hindrance I would say, so I would be happy to try out this option. How did you feel about how much real estate was available for the results list in portrait mode nav menu? I feel like it looks a little tight, and I'm not sure if it would be worth to expand the nav menu (either when the search feature is interacted with or just making it bigger in general). Looking at some more example sites on mobile (https://docs.gitbook.com/, https://www.ign.com/, https://www.gamespot.com/), it looks like some of them have nav menus that are bigger than ours on portrait. What do you think?

**Comment by coiko** [comment]
@KianBadie Yes, I definitely see what you mean.  I think the best would be to expand the nav menu when the search feature is activated, but if it's easier to have it wider all the time (i.e. also in table of contents mode) that's great, too.  Thanks!
