### ISSUE TITLE
Implement search feature

### ISSUE THREAD

**Issue by KianBadie** [caltechlibrary/cell-atlas#24]
Implement search feature on site.

**Comment by coiko** [comment]
@KianBadie This looks great!  I love the animation.

As far as styling, I don't know if this would be feasible/easy to implement, but maybe the border circle could appear on hover (and then expand on click)?  Since we don't enclose other icons in borders, having just the magnifying glass when not selected might be more consistent/cleaner.  (But I think the oval on the full bar looks perfect, style-wise.)  That might also get at your idea of signaling interactivity without having to change the icon color to keep enough contrast from a different background.

The only other thing that struck me was that by putting it in the center of the header, it becomes the most obviously important element, which might not be right for this kind of site (as opposed to something like Amazon).  Could we try moving it over to the left, closer to the nav menu?

I really like the built-in "X" function on the search, so I vote for keeping it.  And I think it's fine not to have a close button and just to close when the user clicks (or tabs) away.  If we did want a manual close option, though, maybe we could use the magnifying glass icon again, analogously to the behavior for expanding/collapsing accordion sections.  One click would open it, and the next would close it.  What do you think?

**Comment by KianBadie** [comment]
@coiko I can try out that styling for the button! In fact, it might actually be easier. I was trying to time the border of the button to reappear after the search bar is closed, but that styling removes that puzzle. And like you said, it get's rid of the contrast problem.

Ah I see what you are saying. Yeah we can move it closer to the nav menu. There's a couple of nuanced ways to do this. First, the three elements (nav, search, and logo) could have equal spacing between them. Because the logo is the longest, the nav and search will naturally be closer to each other. Another way is to have the search menu at a fixed distance from the nav menu button. Lastly, since it won't be centered anymore, the search bar could expand in a specific direction. Since it is favoring left, maybe the nav bar could expand right. Not necessary, but all options to consider. Do you have any thoughts on this?

Also, I realized I might have misinterpreted what you said. When expanded, would the search bar still be centered? If not, the results list will also not be centered anymore.

I think for a lot of expanding/collapsing features, it makes sense to have the button act as a toggle. One thing I was trying to avoid with this feature though is having that icon be interpreted as a "submit search" button. So I am currently on the fence about it and would like to roll the idea around a bit more.

**Comment by coiko** [comment]
Thanks @KianBadie!  I like the idea of the search bar expanding out to the right.  Personally, I think it's fine if the results list is off-center (along with the search bar), but if you prefer to keep it centered, what about having the icon stay where it is when the bar is expanded (so it's always left-of-center but the bar is centered with the other elements when it expands)?

And as for thinking more about toggling the button, sounds good!

**Comment by KianBadie** [comment]
@coiko For sure. If you are ok with the search feature being off centered, then I think either option you mentioned is great and I want to leave it up to your preference! In the end when everything is completed, that will actually be an easy thing to change between if we decide one is better than the other. It's just a matter of moving the anchor (which is the search bar in this case).

**Comment by KianBadie** [comment]
@coiko As a follow up to our previous comments, I implemented both options and here is how they look. Personally, I think the fixed positioning next to the nav makes the header look cleaner. What do you think?

## Fixed next to nav
![search-bar-left](https://user-images.githubusercontent.com/18221058/136637414-0f0565a3-9637-47d0-9701-f8acbd62a830.gif)
## Still centered
![search-bar-centered](https://user-images.githubusercontent.com/18221058/136637419-f8cd919f-8ccf-4af2-90ff-bb53ddae6088.gif)

**Comment by coiko** [comment]
@KianBadie Oh it's perfect!  (Yes, the fixed position next to the nav menu.)  The placement, styling, and behavior all look fantastic. Thank you so much!

**Comment by KianBadie** [comment]
@coiko Sounds good, and no problem!

**Comment by coiko** [comment]
@KianBadie I like that idea!  It would avoid frustration if the user accidentally closed the search bar by clicking somewhere else.

And yes, I think it's fine to leave off the toggle functionality on the search icon.  Thanks!

**Comment by KianBadie** [comment]
Sounds great!

**Comment by KianBadie** [comment]
@coiko Here is how things are looking for the mobile version of the search widget so far! Do you have any suggestions or opinions on what is shown so far?

![search-demo](https://user-images.githubusercontent.com/18221058/137768905-371e23de-0d22-45cd-a941-d2f98de21598.gif)
![search-demo-landscape](https://user-images.githubusercontent.com/18221058/137769399-600c29f0-de5d-4f62-ab2d-7509c49de594.gif)

**Comment by KianBadie** [comment]
@coiko Great and no problem! Unless anything comes up, I plan on merging this today as I think it is in a ready state to be played around with.

**Comment by coiko** [comment]
@KianBadie I think it looks great!  The split-second appearance just seems like part of the whole transition.  Thanks!
