### ISSUE TITLE
Narration feature design

### ISSUE THREAD

**Issue by KianBadie** [caltechlibrary/cell-atlas#29]
Determine design/functionality for narration feature.

**Comment by KianBadie** [comment]
@coiko I got some initial ideas out for how the narration feature could look in the main section on desktop. With this feature, I think the transition to mobile will be identical. These ideas are all just going off of the multiple button shelving/unshelving design we discussed. I can't help but feel that there are better designs for this feature, so I would like to try out some different designs. However, at the moment I am a bit dry on ideas for this so I wanted to get these out there to get some opinions. The last idea in the mocks was to show/hide a full length native audio player. So it would look different on safari, chrome, and firefox.

One important but minor thing I realized is that showing/hiding controls could add height to the main section depending on the title length. I don't think it is a problem, but I wanted to make that known going forward.

[Mocks](https://www.figma.com/proto/PuOTnnRiPxghXq82e3qI85/Narration-Mocks?node-id=3%3A2&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=4%3A75)

**Comment by coiko** [comment]
Thanks @KianBadie!  These are beautiful!  

I like the white options the best.  Maybe we could even combine them, with the hollow icon as the unselected option, expanding into a filled white set when active?  We could also try the same styling as for the search icon, where the circle appears on hover/selection.

I like the minimal controls better than the full native set (even though that has more feature), since the native set takes its own line and is more visually dominant.

What do you think about having the icon aligned to the right of the window (so then the options would expand out to the left)?  It might make it seem more like part of the interface than part of the text, and it might be good if it always appears in the same place on the page?

My only other thought is that maybe the back and forward icons should more obviously indicate that they're skipping 10 or 15s rather than fast-forwarding/rewinding (clearly I've been trained on old analog audio/video players)?  I'm thinking of something like the video streaming controls that show circular arrows around a number.  What do you think?

**Comment by KianBadie** [comment]
@coiko I think having the icon aligned to the right window is a good idea that I would be happy to mock up. In that case, when the controls are expanded it would just force the title to text wrap a line down (if needed)? I will also try to style things as you've described!

Ah yes, I think you are absolutely right! Must have slipped my mind!

**Comment by coiko** [comment]
Thanks @KianBadie!  And yes, I think it's okay if the title wraps to a second line.  Although maybe we should consider having the controls expand below the icon on the title line (like the native player in your mock), since if someone's listening, they probably don't care if the text gets pushed down a line (since they're probably not reading it).  Which way do you think is better?

**Comment by KianBadie** [comment]
@coiko [Here](https://www.figma.com/proto/PuOTnnRiPxghXq82e3qI85/Narration-Mocks?node-id=50%3A252&scaling=min-zoom&page-id=50%3A212) is a link to a new mock that reflects what we are currently.

I do like the idea of having it expand below the title line. In the linked mocks, it actually came out very clean. The thing I like most about it is that it does give room to have an explicit restart button, which was one thing I wanted to discuss. After some thought, having the close/reopening of the controls seemed less appealing since it wasn't explicit how that worked. What are your thoughts on adding one more button in either option (new row or same row)? I'm not sure if I would say it is necessary to have, but I did what to hear your thoughts.

Also, I was also curious on your thoughts on the native controls. Was the amount of functionality overbearing? Or was it more so the styling of the controls? I am wondering because after experimenting with the new row option and thinking about adding another button, I did start to wonder if a custom seek bar/time display would be good. It could be more minimal, maybe just a white text time display (x:xx / y:yy) and a white line with just a white thumb to seek. If anything, that could get rid of the need for a jump back and jump forward button. So it could just be a playback button with the seek bar at the least.

**Comment by coiko** [comment]
@KianBadie Oh I like it!  What about having the controls also aligned on the right (so they're under the open/close icon)?

I also love the custom seek bar - it looks fantastic!  (And it offers much more control than the jump forward/back buttons, as well as the extra information of how long the audio piece is.  And as an added bonus, it obviates the need for a restart button (which otherwise I'm totally in favor of).)  I think it's a winner!

The only thing I might change from the last mock is to replace the stop icon with a play/pause icon.

**Comment by KianBadie** [comment]
@coiko I can try that out! I added 4 more mocks to that same link above. 2 of them right align the controls underneath the narration button. The other 2 left align the controls above the title. It was a spur of the moment idea. Personally, even though it is a bit odd visually for a right aligned control to open something left aligned (since I'm used the the left to right way we read), the left aligned controls below the title seem the cleanest to me. It leaves less empty space and is fitting to me in the flow I expect to read to things. What are your thoughts?

Funny how brainstorming our original ideas led us to a totally new design! I think it is a winner as well!

Ah yes, I think that is a great move as well to replace that icon.

**Comment by coiko** [comment]
@KianBadie Oh that's cool!  I really like the controls opening above the title (since the title is really part of the text).  Could we have the unselected audio icon in line with the title and then move it up with the controls when they open?

I also see why you like the left-aligned controls.  I guess I was thinking about them appearing as a pop-out from the icon selection, so it felt like they were jumping too far to appear on the left.  That's less of an issue now with the longer slider, though, so I think left-aligned is great.  Thanks!

**Comment by KianBadie** [comment]
@coiko That questions was exactly what I was thinking. If I'm understanding you correctly, you are wondering if the narration button can take up space with the title (so that the title would line wrap if it get's too close to the narration button), but then stay in the top right when the title moves down. I have ideas of how to do this that I think will work. If it does work, would the option you described be the most ideal solution?

Ah I see! So currently the options we narrowed down are left aligned custom players either above or below the title?

**Comment by coiko** [comment]
@KianBadie Yes, I think that would be perfect!

**Comment by KianBadie** [comment]
@coiko Awesome! In that case I will try to implement things that way. I'm assuming the same would happen on mobile and in modals (narration button in top right and seek bar appearing above titles). Just to be sure though, I did quickly make some mocks though for [desktop](https://www.figma.com/proto/PuOTnnRiPxghXq82e3qI85/Narration-Mocks?node-id=83%3A460&scaling=min-zoom&page-id=83%3A458) and [mobile](https://www.figma.com/proto/PuOTnnRiPxghXq82e3qI85/Narration-Mocks?node-id=85%3A766&scaling=min-zoom&page-id=83%3A459). 

That just leaves a mock for the "emergency stop" button. It's very simple, but I'll make mocks anyway just so we know what we are getting into. Since the designs are pretty close to being decided, I can start implementing this soon!

**Comment by coiko** [comment]
Thanks @KianBadie!  The mocks look fantastic!  I love the emergency stop button in the Text shelf - it looks really elegant (and also makes it clear that the audio is associated with the text, not the video).  Good luck with the implementation!

**Comment by KianBadie** [comment]
@coiko Awesome! Thank you and I will keep you updated on the progress of that!

Also, I did some quick research to see if audio and video can play at the same time on mobile. Testing on a couple of android/iOS devices, it looks like you can play both at the same time. It looks like the only side affect is to the built in media controls (that show when you swipe down from the top of screen or on the lock menu). On iOS, it seems that once a video is played, it will always show as the currently focused item in those media controls (even if audio is still playing with the video paused). However, after you toggle the video playback once from that menu (which won't affect the video playback since it needs to play in full screen) it will play/pause the audio as needed (while still showing that you are controlling the video). On Android, it looks like it does the more straight forward thing and pauses/resumes whatever current media element was playing (whether it was the audio or video or both). 

I couldn't find anything written on this though, so this was all done from my testing. So unfortunately, I can't give any confirmation yet on predicting the functionality. However, it seems at the least audio and video can be played at the same time on mobile.

**Comment by coiko** [comment]
Sounds great @KianBadie!  Thanks so much for looking into this!
